src/model_controller.py, tests/unit/conftest.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_custom_inference_model.py
If by mistake there's an empty yaml file in the repository, the action will fail with misleading error. The desired functionality is to skip such files and print a proper warning.
* Detect an empty yaml files during loading and print a warning message
* Unit-tests
=> [RAPTOR-8535] Handle properly empty yaml files

README.md, src/model_controller.py, tests/unit/conftest.py
The common glob patterns enable specifying directories on their own, thus only the directory will be included. It has no real meaning in the case of custom inference models - directories are not included, but only files within directories. Therefore, it is required to automatically regard directory paths that are provided by users as being scanned recursively, for both include and exclude patterns.
* Automatically add `**` to paths in the glob pattern lists that ends with `/`
* Unit-tests
=> [RAPTOR-8538] Make directory path in the glob related fields recursive

src/dr_client.py, src/model_controller.py, tests/functional/test_model_github_actions.py
If the user initially creates a model with wrong target name and at the same time the training dataset is also set, than it's no possible for the user to update the target name.
* Change the order of applying changes to the model - first settings and afterwards the training/holdout datasets.
* Make sure to return the response status code from DR in all missing places.
* A functional test.
=> [RAPTOR-8539] Enable model's target name update while training data assignment is involved

src/common/github_env.py, src/custom_models_action.py, src/main.py, src/model_controller.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_custom_inference_model.py
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* Fix the way an output parameter is set.
=> [RAPTOR-8723] Fix deprecating set-output command

src/model_controller.py
When checking if a file should be removed from a model, the local model files are checked against the files that are stored in the model in DR. The issue was that the local file path was extracted incorrectly.
=> [RAPTOR-8726] Fix an invalid path reference for files under model

tests/unit/conftest.py, tests/unit/test_custom_inference_model.py
The issue apply to local development environment only, where the GITHUB_OUTPUT environment variable does not exist in the environment.
=> [RAPTOR-8736] Fix unit-tests that access GITHUB_OUTPUT to save statistics

src/common/http_requester.py
It turned out that using request’s session, can be flaky in slow environment such as US production.
* Replace requests.Session with direct call to requests in http_requester.
=> [RAPTOR-8798] Instead of requests.Session use requests directly

src/dr_client.py
It turns out to be much more robust to wait for a deployment creation completion before trying to configure certain settings in it.
* Add a method to wait for deployment creation completion before returning.
=> [RAPTOR-8802] Wait for a deployment creation completion before update its settings

Makefile, src/dr_client.py, tests/functional/conftest.py
If functional tests are stopped in the middle, there might be remainders in DataRobot account, which will never be tracked. It is essential to clear them up before starting a new session of functional tests.
* Add new methods in DrClient to delete all deployments and models
* Add new global fixture with a session scope and auto use, which will be called to cleanup deployments and models
=> Add global setup fixture to cleanup leftover deployments and models

.github/workflows/workflow.yml
The functional tests in the workflow cannot be executed in parallel, because they work against the same account, but on different ad-hoc workspace tress.
The functional tests in the workflow cannot be executed in parallel, because they work against the same account, but on different ad-hoc workspace tress.
Also, make sure to stop any previous run instead of waiting it to complete. This is useful if a fix was submitted before the previous run was completed.
* Add a concurrency limitation in the workflow YAML file
=> Avoid concurrent runs of the action's workflow

src/dr_client.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_github_actions.py
When trying to run all the functional tests as part of the workflow in GitHub, the `test_e2e_deployment_settings` was failing.  
* Add necessary cleanup fixtures
* Add necessary setup fixtures
=> [RAPTOR-8794] Fix a failure in 'test_e2e_deployment_settings' functional test when executing in GitHub

src/dr_client.py, tests/unit/test_dr_client.py
When setting stability checks, the passing_rate param we have on our example, has the value set to 95. When trying to deploy this definition, the err msg we get is:
```
Error: -28 13:41:02,675 [ERROR]  Custom model version test failed. Response code: 422. Response body: {"message": "Invalid field data", "errors": {"parameters": {"stabilityCheck": {"passingRate": "value is greater than 1.0"}}}}.
Error: Process completed with exit code 166.
```
* Normalize the passing rate value by dividing it by 100
--------------------------------------------
**CAUTION**: changing the state of the checkbox will immediately terminate any previous run of the tests.
=> [RAPTOR-8789] Fix stability check passing rate attribute value

src/dr_client.py, tests/unit/test_dr_client.py
Starting a performance check with a small amount of time, finishes the tests with a warning. However, the custom models action execution results in the following error:
```
Error: -28 13:55:13,335 [ERROR]  Custom model version check failed.
Check: 'performanceCheck'.
Status: warning.
Message: The test was interrupted because it exceeded the allotted testing time (1 minute 40 seconds) for the performance check.
Interruption occurred when the 50 MB sample was tested for performance.
```
* Fix the related method to properly handle custom model testing response.
* Unit tests
=> [RAPTOR-8791] A warning in custom model testing should not be regarded as failure

README.md, src/deployment_controller.py, src/dr_client.py, src/schema_validator.py, tests/deployments/deployment.yaml, tests/functional/test_deployment_github_actions.py
Fix a deployment's actuals association and rename related attributes to better reflect the corresponding attributes in DataRobot.
* Rename association related attributes in the schema.
* Use the `ASSOCIATION_ACTUAL_VALUES_COLUMN_KEY` attribute to associate actuals to a deployment.
* Fix functional tests.
=> [RAPTOR-8863] Fix a deployment actuals association and related attribute names

src/deployment_controller.py, src/deployment_info.py, src/dr_client.py, tests/conftest.py, tests/functional/test_deployment_github_actions.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_dr_client.py
In case there were changes in deployment's settings only, the metric for affected deployments was not updated. With the given fix, this metric will be updated at such scnario.
* Improve the deployment controller to reflect changes in deployment's settings
* Unit and functional tests
=> [RAPTOR-8895] Increase affected deployments metric upon changes in deployment's settings

src/model_controller.py, tests/unit/test_custom_inference_model.py
If a multi-models YAML definition was placed in a sub folder that is not in the root of the models themselves, the model’s directory path was added as a valid file path to the model’s file list.
* Improve the logic to check if a given path equals to the model's directory path.
* Unit tests
=> [RAPTOR-8900] Exclude model's path from model associated files in multi-models YAML definition

README.md, src/schema_validator.py
When the user specify an importance higher than “LOW”, an attempt to create a deployment results in a notification to reviewers to approve the new deployment. When such notification is in pending state, waiting for reviewers, the following weird scenarios may happen:
And attempt to delete such deployment will fail, because the deployment was not created yet.
Any following run of the GitHub action, will try to re-create the deployment, which also result in a failure.
* Add a comment in the `DeploymentSchema` related attribute.
* Add documentation to the README.md
=> [RAPTOR-8910] Document governance (deployment's importance) workflow

src/deployment_controller.py, src/dr_client.py
Apparently, it’s not possible to enable a feature drift before a training data is assigned.
* Reorder DataRobot public API calling's order
* Some renamings.
=> [RAPTOR-8925] Upload learning data before enabling feature drift

README.md, src/dr_client.py, tests/functional/test_deployment_github_actions.py
When there’s an error in a deployment creation from a package, is it desired to print the actual logs that might reveal the root cause of the failure. So, in such failure is it required to make a best effort to fetch and print such logs.
* Add methods to fetch deployment's logs (persistent + runtime)
* Add functional test
=> [RAPTOR-8926] Fetch and print deployment's log in case of a deployment's creation failure

src/dr_client.py, tests/unit/test_dr_client.py
Currently, if a given check if disabled in the definition file, the default is taken from whatever is configured in DataRobot. It is desired that the single source of truth will be the local model definition (YAML).
* Include "skip" configuration value for any check that is disabled or does not exist.
* Unit tests
=> [RAPTOR-9000] Disable any custom model check that is not explicitly enabled

src/dr_client.py, tests/functional/conftest.py
Apparently, in local development, the environment might be reinstalled very often. Consequently, the environment ID, that is set in the deployment YAML file becomes outdated and the failure is weird (404, Not found when trying to created custom model version).
It’ll be best to identify the local development and when preparing the model’s YAML file, make sure to fetch the installed environment and set the proper environment ID in the YAML file.
* Add a fixture to fetch an installed sklearn environment drop-in from DataRobot.
* Use this fixture in the functional tests.
=> [RAPTOR-8896] Fetch an installed sklearn environment drop-in from DR for the functional tests

README.md, src/common/constants.py, src/custom_models_action.py, src/deployment_controller.py, src/metrics.py, src/model_controller.py, tests/conftest.py, tests/functional/test_deployment_github_actions.py, tests/unit/conftest.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_custom_inference_model.py
In addition to the existing metrics a new metric is now provided, which counts the number of models and deployments whose settings were updated.
* Change the term `statistics` to `metrics` all over the place.
* Change the metric names format.
* Refactor the metrics design and put its handling in its own separate module.
* Add new metrics: `models--total-updated-settings` & `deployments--total-updated-settings`.
* Unit & Functional tests.
=> [RAPTOR-8897] Add a metric to count the number of models & deployments whose settings were updated

README.md, action.yml, src/common/exceptions.py, src/common/namepsace.py, src/deployment_info.py, src/dr_client.py, src/main.py, src/model_info.py, src/schema_validator.py, tests/deployments/deployment.yaml, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_github_actions.py, tests/models/py3_sklearn/model.yaml, tests/unit/conftest.py, tests/unit/test_common.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_custom_inference_model.py, tests/unit/test_dr_client.py
The idea is to enable users to provide a namespace, which is a plain string, to the GitHub action (optional input argument), which will be used to isolate all the loaded models and deployments by that namespace. With that the GitHub action is guaranteed to always work with models and deployments that are only in that namespace.
The GitHub action will automatically add the namespace string as a prefix to the user provided ID attribute of every loaded models and deployments. Users will not be required to write the namespace in their YAML definitions.
There are few benefits for such capability:
* Enable to globally isolate models and deployments that were created by different stakeholders.
* A safe guard for individuals as well as groups to avoid collisions.
* Enable to define an isolated …
=> [RAPTOR-9063] Add support for namespaces

README.md, src/common/exceptions.py, src/common/github_env.py, src/common/namepsace.py, src/main.py, src/model_controller.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/unit/conftest.py, tests/unit/test_common.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_dr_client.py
A namespace is a unique string that can be provided as an input argument to the action. The
purpose is to guarantee that the custom model action handles models and deployments that only exist
in the configured namespace. Any other models and deployments that are not in the configured
namespace will remain untouched.
**If not provided, the GitHub repository ID will be used as the namespace.** It means that the custom
models action will process models and deployments that were created from this repository only.
* Add the GitHub repository ID as the default namespace if not provided by the user.
* Unit & Functional tests
**CAUTION**: changing any of the checkbox states will …
=> [RAPTOR-9079] Use GitHub repository ID as the namespace unless it is set by the user

src/dr_client.py, tests/unit/test_dr_client.py
There was an issue in which segment analysis attributes could not be set if the segment analysis was already enabled in a previous run.
* Fix the related functionality to build the segment analysis payload
* Unit tests
=> [RAPTOR-9212] Fix a failure to set segment analysis attributes after it was enabled

src/dr_client.py, src/model_controller.py, tests/functional/test_model_github_actions.py, tests/unit/test_dr_client.py
In the current implementation a major version is created only upon files changes. The logic should be fixed to read the latest version’s frozen status. If it is frozen, then create a new major version, otherwise, create a minor version.
* Set the `isMajorUpdate` attribute according to a previous version's frozen state.
* Functional test
=> [RAPTOR-9253] Fix the formula to set a major update custom model version

action.yml
It turns out that the action definition still declare and use the old statistics metric names. It is required to update to the new schema.
* Update the metric names in the `action.yaml`
=> [RAPTOR-9296] Fix output statistics metric names

src/dr_client.py, tests/unit/test_dr_client.py
This PR fixes a bug of a partial configuration of the custom model checks.
* Add a condition to validate that a check exists in the configuration file.
* Unit test
=> [RPTOR-9297] Fix 'NoneType' object is not subscriptable in custom model checks

src/common/git_model_version.py, src/deployment_controller.py, src/dr_client.py, src/model_controller.py, src/model_info.py, src/schema_validator.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_github_actions.py, tests/functional/test_model_training_holdout_data.py, tests/functional/test_multi_models_definition.py, tests/models/py3_sklearn/model.yaml, tests/unit/conftest.py, tests/unit/test_custom_inference_model.py, tests/unit/test_dr_client.py, tests/unit/test_schema_validator.py
* This PR support for training/holdout data at model's version levels. 
* When defined at version level - the model will be created with the `is_training_data_for_versions_permanently_enabled` set to true.
* The related training/holdout attributes at model vs. modelv's version are mutually exclusive.
* The action will also provide hints for what needs to be done in case of an error - e.g. "Training dataset is expected at the version level. Consider moving the definition to the version section of the model."
=> [RAPTOR-9228] Add support to set training/holdout data at custom model version level

src/dr_client.py, tests/functional/test_deployment_github_actions.py
When there’s an error in a deployment creation from a package, is it desired to print the actual logs that might reveal the root cause of the failure. So, in such failure is it required to make a best effort to fetch and print such logs.
* When creating a deployment, fetch deployment runtime and persistent errors.
* Functional test
=> [RAPTOR-8926] Fetch and print deployment's log in case of a deployment's creation failure (#296)

src/dr_client.py, src/model_controller.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_github_actions.py
Given that a model metadata is not part of  the mode package (.e.g using exclude attribute), and the user creates a commit in which he only enables the custom model testing, make sure to run the custom model testing only if the given version was not tested yet.
* Make sure to trigger a custom model testing even if it there was no changes in its settings nor a new version was created.
=> [RAPTOR-9300] Properly trigger custom model testing even upon a change in the test section only

src/dr_api_attrs.py, src/dr_client.py, tests/unit/test_dr_api_attrs.py, tests/unit/test_dr_client.py
When creating a new custom model, the action maps the TARGET_TYPE values from ModelSchema to values that are expected from the API. This done via MODEL_TARGET_TYPE_MAP in dr_client.py.
The Type map was missing a mapping for Anomaly Detection models. Thus, when using Anomaly Detection as the target type no value was passed to the API leading to an error.
* Add missing mapping attribute to the target type
* Some refactoring concerning mappings between local schema attributes to DataRobot API.
=> [RAPTOR-9312] Add a missing mapping of Anomaly target type + refactoring

src/common/github_env.py, tests/unit/test_common.py, tests/unit/test_dr_api_attrs.py
Apparently, all the functional tests pass with success, but eventually GitHub the following errors:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '-------- custom-model logs --------'
```
This is because GitHub deprecated an old way to output metrics and replaced it with a method that requires special handling to output multi-lines.
* Extend the GitHubEnv::set_output_param to support multlines string value.
* Unit tests
=> [RAPTOR-9319] Add support for multi-lines output message metric 

.github/workflows/workflow.yml, Makefile
It’ll be very helpful to be able to specify the functional tests that will be executed during a PR. This capability will save a lot of time, because running all the functional tests now is about 1.3 hours.
* Update GitHub workflow + Makefile
=> [RAPTOR-9338] Allow users to specify desired functional tests for execution during a PR

src/schema_validator.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_training_holdout_data.py, tests/unit/test_schema_validator.py
Apparently, the related public APIs are in a deprecation phase and instead a work is being done to assign training/holdout data as part of a model version creation/update. In order not to enforce the current API to go into the regular deprecation process, it is required to disable the usage of them. 
Soon the new APIs will be ready and some more work will be required in the GitHub action to remove the old once and start using the new ones.
* Comment out the training/holdout attributes in the model's schema version section.
* For the basic functional test, set the training/holdout data at the model level
* Disable certain related unit-tests
* Disable certain related functional-test
**CAUTION**: …
=> [RAPTOR-9337] Temporarily disable assignment of training/holdout data at model version level

src/deployment_controller.py, src/deployment_info.py, src/dr_client.py, src/model_info.py, src/schema_validator.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_training_holdout_data.py, tests/unit/test_dr_client.py
Until this PR, the reason for replacing a model was hard-coded with a value of "OTHER". With this PR the user can specify the reason for a model's replacement in a deployment by using a specific attribute in the model's metadata YAML file.
* Add a new attribute to the model's schema: `model_replacement_reason`, which can be set with very specific values.
* Some refactoring
* Spelling bug + skip specific undesired functional test
* Unit & functional tests
=> [RAPTOR-9299] Enable users to specify the reason for a model replacement in a deployment

src/dr_client.py, src/model_controller.py, tests/functional/test_model_github_actions.py, tests/unit/test_dr_client.py
Add support to track model’s settings separately from the model’s versions, in order to properly filter out undesired changes when comparing git commits (specifically upon pull-requests merges).
Today, in order to avoid redundant updates of model’s settings, the latest version is updated with the git SHA of the latest changes, even if those changes were in the settings and did not result in a new version.
In order to accomplish it a new attribute was added to the custom inference model entity in DataRobot, to hold information about the git version.
* When looking for affected models the settings and versions are tracked separately.
* Update git information at a model level
* Functional tests
* Unit tests
-------------------------------------------------------------------------------------- …
=> [RAPTOR-9255] Separately track model's settings from model's versions

src/dr_client.py, tests/unit/test_dr_client.py
When fetching entities from DataRobot usually a pagination takes place. The client (GH Action) uses the ‘next’ field to call the followed page url. The url in the 'next' field should not be altered and the call should use it as is. The issue is that the ‘params’ argument is also passed to the request.get method, which result in concatenation of the params to the URL.
* Fix the DrClient pagination method.
=> [RAPTOR-9448] Fix the issue of params arguments that are concatenated to the URL at every paginated call

src/deployment_controller.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/unit/test_custom_inference_deployment.py
The user can delete a model’s definition and create a PR, even if the model is deployed. Because the checks will succeed, the PR can be merged, but the action will fail to delete the model in DataRobot. It is required to notify the user during the PR that the model is deployed and cannot be set for deletion without deleting its associated deployment definition.
* Improve the validation check for deployments.
=> [RAPTOR-9449] Validate that a model's definition is not deleted in a PR while it is deployed

src/dr_api_attrs.py, src/schema_validator.py, tests/functional/test_model_training_holdout_data.py, tests/unit/conftest.py, tests/unit/test_dr_client.py, tests/unit/test_schema_validator.py
The idea is that only attribute names will have the _KEY suffix in their constant names. Value definition will only start with the related attribute name.
* Renaming only
=> [RAPTOR-9562] Rename model/deployment value definitions by removing the '_KEY' suffix

README.md, src/dr_client.py, src/model_info.py, src/schema_validator.py, tests/unit/conftest.py, tests/unit/test_dr_client.py
Lately, we added support for network egress policy in production. It is required to allow users to specify the policy for their custom models.
* Add an egress network policy field to the model schema
* Add the egress network policy attribute when creating a custom model version
* Unit test
=> [RAPTOR-9559] Add support for egress network policy resource in a model version

src/schema_validator.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_training_holdout_data.py, tests/unit/test_schema_validator.py
With the functionality being a GA, to enable users to assign training/holdout datasets at model version level it is required to add this support to the GH action.
* Uncomment related fields in the model's schema
* Functional test
* Unit test
=> [RAPTOR-9580] Enable training/holdout assignment at model version level

src/model_controller.py
During an execution of the functional test `TestDeploymentGitHubActions.test_e2e_deployment_settings[push]` it was detected that a variable is being used before assignment.
* Initialize the related local variable
**NOTE**: to run a certain specifi functional test(s), write a comment that includes the following
pattern `$FUNCTIONAL_TESTS=<test-to-run>`. The workflow will extract whatever test(s) specified
after the assignment sign and will trigger an action to run it. The execution can be viewed under
the `Actions` tab.
=> [RAPTOR-9589] Fix local variable 'training_holdout_updated' referenced before assignment

src/deployment_controller.py, src/schema_validator.py, tests/functional/test_deployment_github_actions.py
Although the default in DR for a deployment's importance is LOW, in order to make sure that user's will work without requiring approvals unless specified otherwise, the default is explicitly set to LOW.
* Set the default importance attribute value in a deployment's settings schema to LOW
* Fix a functional test to not try and change the importance to HIGH, because it results in a test failure due to the need for approval.
**NOTE**: to run a certain specifi functional test(s), write a comment that includes the following
pattern `$FUNCTIONAL_TESTS=<test-to-run>`. The workflow will …
=> Implicitly set a deployment's default importance value to LOW

tests/functional/test_deployment_github_actions.py, tests/models/py3_sklearn/custom.py
The functional test `tests/functional/test_model_github_actions.py::TestModelGitHubActions::test_e2e_pull_request_event_with_multiple_changes` fails with:
```
ERROR    root:main.py:116 Custom model version check failed. model_id: 650c018c004ba77cfd095083, model_version_id: 650c01bf8dfc0831d7448d7d, check: errorCheck, status: failed, 
message: ERROR: Failure when making predictions: Number of features of the model must match the input. 
Model n_features is 33 and input n_features is 34 .
``` 
* Remove `id` column during `transform` to end up with the number of features that the model expects.
is in …
=> [MMM-14420] Fix broken test: test_e2e_pull_request_event_with_multiple_changes

src/dr_client.py, src/model_controller.py, src/model_info.py, src/schema_validator.py, tests/functional/test_model_github_actions.py, tests/unit/test_dr_client.py
As part of the process to support Public Models in DataRobot, we want to make it possible to automatically build and deploy public models. 
In the model yaml, add support for registering custom model versions using:
```
model_registry:
model_name: [DataRobot] Awesome Public Model
```
This should create a new registered model called [DataRobot] Awesome Public Model if it does not exist. If it already exists, a new registered model version should be added if it is not already present. …
=> [MMM-14420] Add Registered model support

src/dr_client.py, src/model_controller.py, src/model_info.py, src/schema_validator.py, tests/functional/test_model_github_actions.py, tests/unit/test_dr_client.py
For the global models project, we want to support making registered models global.
*  Add `global` boolean value to `model_registry` in the schema.
* Update `global` flag in model controller.
=> [MMM-14942] Support toggling registered model global flag

src/dr_client.py, src/model_controller.py, src/model_info.py, src/schema_validator.py, tests/unit/test_dr_client.py
We want to be able to set the description for global models.
Changed method `set_registered_model_global` into a more generic method `update_registered_model` that supports updating properties for a registered model.
=> [MMM-14942] Support updating registered model description

src/dr_client.py, tests/conftest.py, tests/functional/test_deployment_github_actions.py, tests/unit/test_dr_client.py
Previously, users could create a model package and immediately proceed to create deployment without waiting for successful package creation. This is no longer permitted; users must wait for the model package to build successfully before deploying.
* Wait for a successful model's package creation, before proceeding to deployment's creation.
* One bug fix regarding to Enum value.
* Minor linting fixes.
----------------------------------------------------------------------------------------------
pattern `$FUNCTIONAL_TESTS=<tests-to-run>`. The test(s) specified after the assignment …
=> [RAPTOR-12005] Custom Models Action: Wait for successful model package creation before deploying

tests/functional/test_deployment_github_actions.py, tests/models/py3_sklearn/custom.py
Previously, the tests used a custom model that included a generated scikit-learn model artifact. This caused incompatibility with newer drop-in execution environments due to updated scikit-learn versions. However, for testing purposes, using a model artifact is unnecessary. A dummy model can be used instead.
* Remove the `sklearn_reg.pkl` model artifact and instead load a dummy model. …
=> [RAPTOR-12007] Custom Models Action: Make model example dummy to avoid compatibility with a given ML package

tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_training_holdout_data.py
Training and holdout dataset assignments are now set by default at the model version level in DataRobot. As a result, custom model actions should be adjusted to test cases at the model version level only.
* Remove training / holdeout dataset assignment tests at the model's level.
* Refactor the code to reflect the given change.
=> [RAPTOR-12008] Custom Models Action: Remove training/holdout tests at model level as DataRobot defaults to model version

README.md, action.yml, src/main.py, src/model_controller.py, tests/unit/conftest.py, tests/unit/test_custom_inference_model.py, tests/unit/test_yaml_exclusion.py
Allow excluding `.yaml` / `.yml` files from being picked up by the GH action, using a regex parameter.
=> [BUZZOK-25903] Add `--exclude`, allowing exclusion of model yaml files

src/model_controller.py
When no `--exclude` is supplied, the attribute will exist but the value will be `None`, which leads to attempts to `re.compile(None)`.
=> [BUZZOK-25903] Fix for when exclude is not passed
