datarobot-oss/custom-models-action

tests/models/py3_sklearn/README.md
=> [RAPTOR-8541] Fix references in the custom inference model README.md under tests

tests/functional/conftest.py
A new dedicate account was created is DR Prod-US, which is used by the functional tests to verify pull requests.
* A new dedicated account was added to US-Prod
* Use certificate verification when testing against an official DR app
=> [RAPTOR-8542] Add dedicated account in DR Prod-US for the functional test

src/model_controller.py
Add more debug logs for better visibility
=> [RAPTOR-8725] Add more debug logs for better visibility

bin/create_release.py
Add a new script that does validations and create a release by adding a tag in the main branch and push it to the remote.
=> [RAPTOR-8731] Add a script to create a release

src/dr_client.py, src/model_controller.py, tests/conftest.py, tests/functional/test_model_github_actions.py, tests/unit/conftest.py, tests/unit/test_dr_client.py
If the user adds a `requirements.txt` file to the model, than a dedicated environment is automatically built, which includes the dependencies that are specified in that file. The new environment will be associated with the given custom model version.
=> [RAPTOR-8732] Add support to a model version's dependency environment

README.md
Add a note about newer versions in the README.md file
* Update the README.md
=> [RAPTOR-8741] Add a note about newer versions in the README.md file

action.yml
* The name in the action’s yaml file should be renamed to “Custom Models Action”.
* Add a branding section to the action’s yaml file to set the icon and color.
=> [RAPTOR-8766] Set proper name to the action and add branding section

README.md
Add a “Quick Start” section to the README.md to quickly on-board newcomers.
=> [RAPTOR-8767] Add a 'Quick Start' section to the README.md

Makefile
Add a timestamp and severity for for the printed logs.
=> [RAPTOR-8805] Improve logging format that are printed during functional tests

.github/pull_request_template.md, .github/workflows/workflow.yml
Provide a friendly UI in the PR to run all the functional tests.
-------------------------------------------------
**CAUTION**: changing the state of the checkbox will immediately terminate any previous run of the tests.
=> [RAPTOR-8786] Add support to run all the functional tests in a PR

.github/workflows/workflow.yml
Currently a description that contains the '`' (back-tick) char is read incorrectly, trying to interpret it as a command.
```
Code block
```
--------------------------------------------
**CAUTION**: changing the state of the checkbox will immediately terminate any previous run of the tests.
=> [RAPTOR-8808] Fix the workflow to correctly read a description body ignoring special characters

src/dr_client.py, src/model_controller.py, tests/unit/test_dr_client.py
=> [RAPTOR-8791] Improve custom model test logging

README.md
Fix some small issues in the README
* The uses should refer to datarobot-oss
* Fix the latest tags in the uses
* Rename job/step names and IDs
* Fix alignment in the YAML examples in the version section
* Fix the metrics results references
=> [RAPTOR-8799] Fix names, references and alignment in the README.md file

README.md, bin/create_release_tag.py
It is desired to validate that the tag references in the README.md are updated and point to the latest version.
* Add a validation (and fix) method to check / fix tags in the README.md
=> [RAPTOR-8813] Improve the script to create a release tag by also validating the README.md

.github/workflows/workflow.yml
Optional spaces may be added inside the brackets, where the check box is set, when analyzing the pull-request description.
Although such spaces are not expected and will not be properly handled by GitHub, the user may add them anyway. 
Take into account spaces inside the brackets.
=> [RAPTOR-8814] Improve the regex pattern in the workflow to check the check-boxes in a pr doc

README.md, RELEASES.md
Documentation review of README.md.
Proofread text, reformat document, and add links to relevant resources.
=> [DOC-4805] Custom Model Action Docs

src/deployment_controller.py, src/dr_client.py, tests/conftest.py, tests/deployments/deployment.yaml, tests/functional/test_deployment_github_actions.py
Few deployment's attributes were not updated upon changes. Although, they are regarded as deployment's settings, they are updated via a different route.
* Add support to update `description` and `importance` attributes in a deployment,
* Update related functional tests.
=> [RAPTOR-8854] Update deployment's description and importance upon changes

README.md, src/dr_client.py
* Add some informative logs for better transparency 
=> [RAPTOR-8924] Add more valuable information to the README.md and some logs

src/dr_client.py, tests/functional/test_deployment_github_actions.py
=> [RAPTOR-8926] Improve deployment's creation log handling

src/model_controller.py
Apparently, when using the route: `GET customModelDeployments/` with input param `customModelIds`, in certain scenarios, the returned deployments do not comply with the requested `customModelIds` thus more deployments are returned.
It results in a bug in the custom models action. 
* Filter out unexpected deployments within the delete operation.
=> [RAPTOR-8935] Overcome an invalid response from DataRobot of deployments for given models

bin/create_release_tag.py
=> [RAPTOR-8944] Add integrity check in the release tool to validate that local and remote master branches are aligned

src/dr_client.py
During testings against DataRobot US production, a deployment creation was successful after more than 10 minutes. The GA action indicated a failure due to a timeout (10 minutes), but apparently the creation was completed afterwards with success. 
When the servers are not busy, this operation may take around 20 seconds.
It is required to increase the timeout upon which a failure will be declared. 
* Set the time to wait for deployment creation to `2 * default = 1200 sec`
=> [RAPTOR-8967] Increase the time to wait for deployment creation

README.md
There are 2 issues to fix in the README:
* The default configuration (EngConfig) for the custom inference models replicas limit in DR SaaS is 2. In the custom models action README doc, the example shows 3 for the corresponding configuration value. It is required to change it to 2 in order to avoid users getting potential errors when just bulk copying parts of the yaml.
* The minimum amount of memory for custom inference models in DR is 128 Mega Bytes. In the README files, the numbers are 100Mi. It is required to change them to comply with the default minimum in DR.
=> [RAPTOR-9189] Update proper resource configuration values in the README

bin/create_release_tag.py
The changes are as follows:
* Update the tag reference in the README.md before verifying integrity
* Move the releases history check into the integrity validation phase
* Replace the exception classes with AssertionError
* Some refactoring to simplify the code
=> [RAPTOR-9190] Improve the create release script

README.md
The segment analysis `attributes` section in the deployment definition example was incorrect and could not be copies as is, because it couldn't work.
* Comment out the segment analysis `attributes` section in the deployment definition example, and add proper explanation.
=> [RAPTOR-9213] Update the segment analysis example in the README.md

src/deployment_controller.py, src/dr_api_attrs.py, src/dr_client.py, src/model_controller.py, src/model_info.py, tests/functional/conftest.py, tests/functional/test_deployment_github_actions.py, tests/functional/test_model_github_actions.py, tests/unit/test_common.py, tests/unit/test_custom_inference_deployment.py, tests/unit/test_dr_client.py
Make sure to track the settings section only in the model's definition and consequently update the relevant settings upon changes.
* Detect changes in the settings section only of a model's metadata
* Some refactoring
* Unit tests
=> [RAPTOR-9254] Avoid marking settings changes for changes in attributes outside the settings section

README.md, RELEASES.md
=> Update README.md + RELEASES.md

README.md
Apparently, the minimum required memory for custom model tests is 256Mi, so updating the README.md accordingly.
=> [RAPTOR-9500] Update the example in README.md with proper memory values

bin/create_release_tag.py
The idea is to be able to create a release in a feature branch, which will include the update for the [README.md](http://readme.md/) and [RELEASES.md](http://releases.md/), without creating a tag. This will allow to run all the functional tests before merging.
After merging, there will be another part that just creates the tag.
It can be in accomplished in the same script or just split it into two scripts.
=> [RAPTOR-9376] Divid the release creation script into two functional logical parts

.github/pull_request_template.md
Using comments, it is possible to run certain functional test/tests. The workflow looks for the `$FUNCTIONAL_TESTS=` pattern in a comment, extract whatever found after the assignment sign and add it to the list of tests to run. A GitHub action is then invoked to runt those tests.
* Pull-request template
=> [RAPTOR-9557] Add a description to the pull-request template for how to run specific funcitonal test(s)

.github/pull_request_template.md
**NOTE**: to run a certain specifi functional test(s), write a comment that includes the following
pattern `$FUNCTIONAL_TESTS=<test-to-run>`. The workflow will extract whatever test(s) specified
after the assignment sign and will trigger an action to run it. The execution can be viewed under
the `Actions` tab.
=> [RAPTOR-9592] Fix a typo and improve a note in the pull-request template

README.md, RELEASES.md
Release v1.6.0
**NOTE**: to run a certain specifi functional test(s), write a comment that includes the following
pattern `$FUNCTIONAL_TESTS=<test-to-run>`. The workflow will extract whatever test(s) specified
after the assignment sign and will trigger an action to run it. The execution can be viewed under
the `Actions` tab.
=> [RAPTOR-9583] Update README.md + RELEASES.md

src/model_controller.py
Apply model changes before creating a new version to ensure all fixes (e.g., target name adjustments) are in place. This prevents issues that could cause version creation to fail.
* Move the code block that creates/updates model before creation of a new model's version.
=> Custom Models Action: Update model settings before creating a new version

README.md, RELEASES.md, pyproject.toml
Release v1.6.1
* Update README.md + RELEASES.md
=> [RAPTOR-11998] Update README.md + RELEASES.md
